// Regenerates src/data/pandals.ts and the optimised WebP images from the
// original static site kept in legacy/. Run with: npm run build:data
import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';
import { STATION_LIST } from '../src/data/metroLines.ts';

const root = path.resolve(import.meta.dirname, '..');
const legacy = fs.readFileSync(path.join(root, 'legacy/script.js'), 'utf8');
const start = legacy.indexOf('const PANDALS_DATA = ') + 'const PANDALS_DATA = '.length;
const end = legacy.indexOf('// 2026 Theme Gallery');
const raw = JSON.parse(legacy.slice(start, end).trim().replace(/;\s*$/, ''));

const byName = new Map(STATION_LIST.map((s) => [s.name, s]));
const slug = (s) =>
  s
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
const hash = (s) => {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 16777619);
  return (h >>> 0) / 4294967295;
};
// Stations whose western side is the Hooghly: keep far markers out of the river.
const RIVERSIDE = new Set(['baranagar', 'shobhabazar-sutanuti', 'girish-park', 'mahatma-gandhi-road', 'dakshineswar']);

// The source list pads missing fields with stock values. They are stripped here so
// the UI can show an honest "not yet known" state instead of repeating filler.
const PLACEHOLDER_THEME = 'Sharad Utsav 2026';
const BOILERPLATE = [
  'Vibrant community Sharodotsav mandap organized with festive illumination, cultural presentations and community bonding.',
  'Historic family heritage celebration observing traditional rituals, devotional arati and classical Ekchala pratima.',
];
const ACCESS = { Auto: 'auto', Cab: 'cab' };
// Corrections learned after the source list was compiled, keyed by pandal id and
// written with the source's own field names. Note where each one came from.
const UPDATES = {
  // Theme named in a first-look reel by @kolkatar_golpo, 7 Oct 2026 (instagram.com/reel/DeMgwRVN3vQ).
  'behala-notun-dal': { theme: 'Baro Mashe Tero Parbon (Twelve months, thirteen festivals)', announcedTheme: true },
};

const squash = (x) => x.toLowerCase().replace(/[^a-z0-9]/g, '');

const hoursOf = (t) => (t.startsWith('Open 24') ? '24h' : t.startsWith('Morning 8') ? 'ritual' : 'day');

const seen = new Map();
const pandals = raw.map((p) => {
  const st = byName.get(p.station);
  if (!st) throw new Error(`Unknown station: ${p.station}`);
  let id = slug(p.name);
  if (seen.has(id)) id = `${id}-${st.id}`;
  if (seen.has(id)) id = `${id}-${p.id}`;
  seen.set(id, true);
  Object.assign(p, UPDATES[id]);

  // No surveyed coordinates exist in the source list, so each marker is placed
  // at its stated distance from the station on a stable pseudo-random bearing.
  let bearing = hash(id) * Math.PI * 2;
  if (RIVERSIDE.has(st.id) && Math.sin(bearing) < 0 && p.distance > 0.8) bearing = -bearing;
  const crow = p.distance * 0.8;
  const latitude = st.lat + (crow * Math.cos(bearing)) / 111;
  const longitude = st.lng + (crow * Math.sin(bearing)) / (111 * Math.cos((st.lat * Math.PI) / 180));

  const image = path.basename(p.image, '.jpg');
  // A photo counts as this pandal's own only when the file is named after it;
  // otherwise the source reused a stock picture of a different pandal.
  const hasPhoto = squash(p.name).includes(squash(image));
  const access = ACCESS[p.description.trim()];
  const description = access || BOILERPLATE.includes(p.description.trim()) ? '' : p.description.trim();

  const tags = [];
  if (p.announcedTheme) tags.push('2026 Theme');
  if (p.traditional) tags.push('Traditional');
  if (p.themeCategory === 'Traditional Bonedi Bari' && /bari|bati|rajbari|family/i.test(p.name + p.description))
    tags.push('Bonedi Bari');
  if (p.vip) tags.push('VIP Pass');
  if (p.petpujo) tags.push('Petpujo');
  if (p.popularity >= 85) tags.push('Popular');

  return {
    id,
    name: p.name,
    station: st.name,
    stationId: st.id,
    line: p.line,
    distanceKm: p.distance,
    walkingMinutes: p.walkingMinutes,
    theme: p.theme === PLACEHOLDER_THEME ? '' : p.theme,
    category: p.themeCategory,
    popularity: p.popularity,
    image,
    hasPhoto,
    description,
    ...(access ? { access } : {}),
    artist: p.artist,
    darshanTime: p.darshanTime,
    hours: hoursOf(p.darshanTime),
    metroExit: p.metroExit,
    latitude: +latitude.toFixed(5),
    longitude: +longitude.toFixed(5),
    tags,
    mapUrl: `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(
      `${p.name} Durga Puja, ${st.area ?? st.name}, Kolkata`,
    )}&travelmode=walking`,
    traditional: p.traditional,
    theme2026: p.announcedTheme,
    vip: p.vip,
    petpujo: p.petpujo,
  };
});

fs.writeFileSync(
  path.join(root, 'src/data/pandals.ts'),
  `// GENERATED by scripts/build-data.mjs from legacy/script.js — do not edit by hand.\nimport type { Pandal } from './types';\n\nexport const PANDALS: Pandal[] = ${JSON.stringify(pandals, null, 1)};\n`,
);
console.log(`pandals.ts: ${pandals.length} records`);

if (!process.argv.includes('--no-images')) {
  const src = path.join(root, 'legacy/images');
  const out = path.join(root, 'public/img');
  fs.mkdirSync(out, { recursive: true });
  for (const f of fs.readdirSync(src).filter((f) => f.endsWith('.jpg'))) {
    const base = path.basename(f, '.jpg');
    for (const w of [480, 1200]) {
      await sharp(path.join(src, f))
        .resize({ width: w, withoutEnlargement: true })
        .webp({ quality: w === 480 ? 68 : 74 })
        .toFile(path.join(out, `${base}-${w}.webp`));
    }
  }
  // Creator portrait, shown on the About page and in the footer.
  const portrait = path.join(root, 'myphoto/Sayan.jpeg');
  if (fs.existsSync(portrait)) {
    for (const w of [480, 1200])
      await sharp(portrait).rotate().resize({ width: w, withoutEnlargement: true }).webp({ quality: 80 }).toFile(path.join(out, `sayan-${w}.webp`));
  }
  // Social share card.
  const title = Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630">
      <defs><linearGradient id="g" x1="0" x2="1"><stop offset="0" stop-color="#120909" stop-opacity=".25"/><stop offset=".55" stop-color="#120909" stop-opacity=".92"/></linearGradient></defs>
      <rect width="1200" height="630" fill="url(#g)"/>
      <text x="1120" y="250" text-anchor="end" font-family="Georgia, serif" font-size="34" letter-spacing="8" fill="#DDAA44">MEETING THAKUR IN THE METRO</text>
      <text x="1120" y="350" text-anchor="end" font-family="Georgia, serif" font-size="92" font-weight="700" fill="#FFF4E6">PUJO BY METRO</text>
      <text x="1120" y="470" text-anchor="end" font-family="Georgia, serif" font-size="120" font-weight="700" fill="#FFD66B">2026</text>
    </svg>`,
  );
  await sharp(path.join(src, 'sreebhumi.jpg'))
    .resize({ width: 1200, height: 630, fit: 'cover', position: 'top' })
    .composite([{ input: title }])
    .jpeg({ quality: 82 })
    .toFile(path.join(root, 'public/og.jpg'));
  console.log('images: done');
}
